name: Generate Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: |
      github.event.pull_request.merged == true &&
      ${{ !contains(github.event.pull_request.title, '[Chore] Update changelog') }}
    name: SemVer release
    outputs:
      CHANGELOG: ${{ steps.generate-changelog.outputs.CHANGELOG }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions

      - name: Bump release
        id: bump-release
        uses: cocogitto/cocogitto-action@v3.6
        with:
          git-user-email: "github-actions@github.com"
          git-user: "github-actions"
          check-latest-tag-only: true
          release: true

      - name: Generate Changelog
        id: generate-changelog
        run: |
          echo 'changelog<<EOF' >> $GITHUB_OUTPUT
          cog changelog --at ${{ steps.bump-release.outputs.version }} -t full_hash >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update changelog"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: chore/update-changelog
          delete-branch: true
          title: "chore(release): update changelog for ${{ steps.bump-release.outputs.version }}"
          body: ${{ steps.generate-changelog.outputs.changelog }}
          labels: |
            documentation
            automated pr
          assignees: cyboooooorg
          reviewers: cyboooooorg
          draft: false

      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.generate-changelog.outputs.CHANGELOG }}
          tag_name: ${{ steps.bump-release.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto -d "${{ steps.create-pull-request.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
